version: '3.8'

services:
  app:
    build: .
    container_name: urlshortener-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      APP_SHORT_BASE_URL: http://localhost:8080

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rufan2006PostgreSql
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
